In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\sddan\Downloads\messy_employee_data.csv", encoding="latin1")

In [2]:
df.head()

,EmployeeID,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating,ExperienceYears
0,1714,Pooja Reddy,36,Mumbai,Operations,NaN,2020-02-16,pooja.reddy28@gmail.com,4.0,14.1
1,1978,Yash Malhotra,25,Bangalore,Hr,75830,11/27/2016,yash.malhotra25@gmail.com,3.0,19.6
2,1936,Swati Malhotra,NaN,Nagpur,IT,57068,25 Jan 2019,swati.malhotra79@gmail.com,5.0,12.6
3,1866,Harsh Verma,28,MUMBAI,HR,58455,2017-01-10,harsh.verma88@gmail.com,1.0,9.7
4,1700,Tanvi Rao,37,pune,IT,43332,2015-06-28,tanvi.rao94@gmail.com,5.0,20.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1090 entries, 0 to 1089
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         1090 non-null   int64
 1   Name               1090 non-null   object
 2   Age                999 non-null    object
 3   City               1056 non-null   object
 4   Department         1090 non-null   object
 5   Salary             1020 non-null   object
 6   JoinDate           1030 non-null   object
 7   Email              1003 non-null   object
 8   PerformanceRating  1014 non-null   float64
 9   ExperienceYears    1044 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 85.3+ KB

In [4]:
df.isnull().sum().sum()

np.int64(464)

In [5]:
df.duplicated().sum()

np.int64(39)

In [6]:
df = df.drop_duplicates()

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1051 entries, 0 to 1089
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         1051 non-null   int64
 1   Name               1051 non-null   object
 2   Age                966 non-null    object
 3   City               1018 non-null   object
 4   Department         1051 non-null   object
 5   Salary             984 non-null    object
 6   JoinDate           993 non-null    object
 7   Email              967 non-null    object
 8   PerformanceRating  977 non-null    float64
 9   ExperienceYears    1008 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 90.3+ KB

In [9]:
df.isnull().sum()

EmployeeID            0
Name                  0
Age                  85
City                 33
Department            0
Salary               67
JoinDate             58
Email                84
PerformanceRating    74
ExperienceYears      43
dtype: int64

In [10]:
df.head()

,EmployeeID,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating,ExperienceYears
0,1714,Pooja Reddy,36,Mumbai,Operations,NaN,2020-02-16,pooja.reddy28@gmail.com,4.0,14.1
1,1978,Yash Malhotra,25,Bangalore,Hr,75830,11/27/2016,yash.malhotra25@gmail.com,3.0,19.6
2,1936,Swati Malhotra,NaN,Nagpur,IT,57068,25 Jan 2019,swati.malhotra79@gmail.com,5.0,12.6
3,1866,Harsh Verma,28,MUMBAI,HR,58455,2017-01-10,harsh.verma88@gmail.com,1.0,9.7
4,1700,Tanvi Rao,37,pune,IT,43332,2015-06-28,tanvi.rao94@gmail.com,5.0,20.0

In [11]:
df["Salary"] = df["Salary"].astype(str).str.replace(r"[^\d.]", "", regex=True)
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")

In [12]:
df.head(20)

,EmployeeID,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating,ExperienceYears
0,1714,Pooja Reddy,36,Mumbai,Operations,NaN,2020-02-16,pooja.reddy28@gmail.com,4.0,14.1
1,1978,Yash Malhotra,25,Bangalore,Hr,75830.0,11/27/2016,yash.malhotra25@gmail.com,3.0,19.6
2,1936,Swati Malhotra,NaN,Nagpur,IT,57068.0,25 Jan 2019,swati.malhotra79@gmail.com,5.0,12.6
3,1866,Harsh Verma,28,MUMBAI,HR,58455.0,2017-01-10,harsh.verma88@gmail.com,1.0,9.7
4,1700,Tanvi Rao,37,pune,IT,43332.0,2015-06-28,tanvi.rao94@gmail.com,5.0,20.0
5,1736,Abhishek Rao,28,Delhi,Finance,95997.0,2016-12-06,abhishek.rao19@gmail.com,4.0,1.9
6,1099,Rahul Saxena,49,Chennai,IT,89397.0,2020-07-11,rahul.saxena15@gmail.com,NaN,10.4
7,1403,Vikram Pillai,32,Hyderabad,Operations,101522.0,25-02-2024,vikram.pillai99@gmail.com,4.0,13.2
8,1357,Shreya Verma,37,Mumbai,sales,46302.0,2024-07-06,shreya.verma70@gmail.com,2.0,2.1
9,1755,Meera Kapoor,52,Delhi,Hr,149714.0,2023-06-01,meera.kapoor65@gmail.com,3.0,9.8
10,1034,Nikhil Iyer,23,NaN,Marketing,22671.0,08-03-2024,nikhil.iyer73@gmail.com,4.0,15.3
11,1525,Ananya Malhotra,24,Chennai,IT,NaN,27 Jan 2021,ananya.malhotra78@gmail.com,5.0,14.0
12,1090,Bhavna Mehta,29,Pune,sales,38191.0,NaN,bhavnamehtagmail.com,2.0,14.5
13,1523,Karan Singh,twenty five,Delhi,Finance,23888.0,2024-04-16,karan.singh2@gmail.com,NaN,0.1
14,1983,Gaurav Kumar,47,pune,HR,92805.0,2016-12-28,gaurav.kumar61@gmail.com,1.0,11.3
15,1742,Abhishek Gupta,53,Delhi,Hr,90481.0,2016-01-15,abhishek.gupta33@gmail.com,2.0,13.0
16,1053,Amit Chopra,55,Hyderabad,Operations,148552.0,13-10-2018,amit.chopra6@gmail.com,4.0,16.2
17,1851,Kirti Pillai,39,Delhi,Marketing,34058.0,20-01-2015,NaN,1.0,7.6
18,1200,Gaurav Rao,38,Nagpur,IT,65061.0,2023-07-25,gaurav.rao50@gmail.com,4.0,13.7
19,2047,Nikhil Desai,35,Nagpur,Hr,142225.0,06-09-2015,NaN,4.0,9.5

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1051 entries, 0 to 1089
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         1051 non-null   int64
 1   Name               1051 non-null   object
 2   Age                966 non-null    object
 3   City               1018 non-null   object
 4   Department         1051 non-null   object
 5   Salary             951 non-null    float64
 6   JoinDate           993 non-null    object
 7   Email              967 non-null    object
 8   PerformanceRating  977 non-null    float64
 9   ExperienceYears    1008 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 90.3+ KB

In [14]:
df.tail(20)

,EmployeeID,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating,ExperienceYears
1069,1290,Swati Reddy,24,Bangalore,IT,76906.0,1/6/2020,swati.reddy51@gmail.com,1.0,11.6
1070,1763,Rekha Joshi,26,pune,IT,22077.0,21 Jan 2019,NaN,2.0,2.6
1071,1949,Sohail Iyer,26,Ahmedabad,sales,114492.0,9/3/2025,sohail.iyer22@gmail.com,3.0,NaN
1072,1183,Anita Singh,40,Bangalore,Sales,132272.0,3/3/2020,anita.singh51@gmail.com,3.0,19.8
1074,2030,Nikhil Bhat,44,Hyderabad,HR,23544.0,2/24/2019,NaN,1.0,7.2
1075,1250,Simran Singh,NaN,Jaipur,IT,67118.0,24-11-2017,simran.singh58@gmail.com,3.0,2.2
1076,1823,Preeti Kapoor,44,Bangalore,Hr,88214.0,11 Jan 2015,NaN,3.0,19.9
1077,1940,Jyoti Reddy,27,Pune,IT,NaN,15 Jan 2025,jyotireddygmail.com,5.0,16.1
1078,1391,Vivek Rao,29,Chennai,Finance,103394.0,10-01-2020,vivek.rao10@gmail.com,2.0,12.0
1079,1904,Pooja Pillai,52,Hyderabad,IT,50816.0,4/20/2019,pooja.pillai77@gmail.com,4.0,2.0
1080,1730,Rajesh Saxena,44,pune,Operations,89796.0,2021-04-28,rajesh.saxena37@gmail.com,4.0,17.5
1081,1554,Rakesh Singh,21,Delhi,Marketing,87412.0,4 Jan 2017,NaN,3.0,7.9
1082,1366,Anjali Pillai,34,Mumbai,Hr,51359.0,NaN,anjali.pillai64@gmail.com,1.0,15.7
1083,1345,Sohail Patel,48 yrs,Bangalore,IT,79558.0,7/18/2023,sohail.patel29@gmail.com,5.0,NaN
1084,1535,Nikhil Malhotra,54,MUMBAI,Marketing,91828.0,05-02-2021,nikhil.malhotra7@gmail.com,3.0,3.3
1085,1919,Meera Desai,55,Kolkata,sales,56477.0,26-06-2016,meera.desai25@gmail.com,3.0,18.2
1086,1211,Vivek Nair,40,Jaipur,Marketing,125569.0,22-07-2024,vivek.nair4@gmail.com,3.0,8.4
1087,1502,Sameer Bhat,-31,Delhi,Hr,62731.0,06-08-2021,sameer.bhat60@gmail.com,NaN,13.5
1088,1537,Sneha Gupta,51,Mumbai,IT,105209.0,14 Jan 2020,sneha.gupta52@gmail.com,1.0,9.8
1089,1175,Vishal Sharma,43,Ahmedabad,Finance,36637.0,12/4/2019,NaN,3.0,5.3

In [15]:
df["Age"] = df["Age"].astype(str).str.replace("-","", regex=False)

In [16]:
df[df["Age"].str.contains("[a-zA-Z]",regex=True, na=False)]["Age"].unique()

array(['nan', 'twenty five', '50 yrs', '25 yrs', '42 yrs', '43 yrs',
       '30 yrs', '26 yrs', '39 yrs', '34 yrs', '37 yrs', '23 yrs',
       '58 yrs', '22 yrs', '55 yrs', '41 yrs', '53 yrs', '57 yrs',
       '40 yrs', '28 yrs', '36 yrs', '51 yrs', '31 yrs', '29 yrs',
       '46 yrs', '48 yrs'], dtype=object)

In [17]:
df["Age"] = df["Age"].str.replace("yrs","", regex=False).str.replace("twenty five","25", regex=False)

In [18]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [19]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [20]:
df.isnull().sum()

EmployeeID            0
Name                  0
Age                   0
City                 33
Department            0
Salary                0
JoinDate             58
Email                84
PerformanceRating    74
ExperienceYears      43
dtype: int64

In [21]:
import numpy as np
df.loc[(df["PerformanceRating"] < 1) | (df["PerformanceRating"] > 5), "PerformanceRating"]=np.nan
df["PerformanceRating"] = df["PerformanceRating"].fillna(df["PerformanceRating"].median())

In [22]:
df["ExperienceYears"].unique()

array(['14.1', '19.6', '12.6', '9.7', '20.0', '1.9', '10.4', '13.2',
       '2.1', '9.8', '15.3', '14.0', '14.5', '0.1', '11.3', '13.0',
       '16.2', '7.6', '13.7', '9.5', '8.3', 'five', nan, '13.1', '19.4',
       '16.8', '6.7', '16.5', '2.8', '18.1', '12.4', '1.0', '15.8',
       '10.0', '0.6', '10.6', '18.3', '5.2', '0.5', '4.1', '12.9', '15.0',
       '9.9', '10.7', '5.3', '17.2', '0.8', '13.4', '7.7', '1.3', '15.6',
       '15.4', '19.9', '14.3', '0.0', '5.8', '18.4', '7.2', '15.9', '3.0',
       '17.8', '4.7', '11.0', '1.1', '4.4', '11.7', '11.9', '8.6', '6.6',
       '8.8', '2.9', '2.6', '13.3', '12.8', '10.8', '8.9', '4.8', '14.7',
       '3.7', '12.0', '6.9', '0.4', '1.2', '7.3', '19.7', '9.3', '0.7',
       '11.6', '3.9', '7.8', '18.0', '6.8', '13.8', '16.3', '1.8', '11.5',
       '12.1', '16.4', '4.5', '5.7', '19.3', '18.8', '15.2', '19.0',
       '8.4', '0.9', '14.9', '2.2', '7.4', '4.9', '17.1', '9.1', '12.2',
       '1.7', '10.9', '16.1', '16.0', '8.1', '2.5', '1.6', '3.1', '14.6',
       '8.2', '6.1', '7.0', '17.3', '18.9', '9.0', '8.0', '3.5', '6.2',
       '2.7', '11.1', '8.5', '2.4', '11.8', '17.7', '19.5', '16.7',
       '13.9', '7.9', '4.6', '5.5', '17.6', '6.4', '10.2', '9.4', '5.4',
       '6.3', '2.3', '6.5', '14.4', '10.3', '1.5', '18.2', '16.6', '4.3',
       '19.1', '14.2', '13.6', '3.6', '18.6', '4.2', '3.8', '0.2', '12.3',
       '4.0', '3.4', '9.6', '15.5', '5.9', '10.1', '17.5', '2.0', '12.5',
       '18.5', '19.2', '9.2', '11.2', '18.7', '7.5', '13.5', '14.8',
       '17.0', '12.7', '0.3', '3.3', '15.7', '17.4', '10.5', '15.1',
       '5.6', '6.0', '8.7', '1.4', '5.0', '7.1', '3.2', '16.9', '11.4',
       '17.9', '19.8'], dtype=object)

In [23]:
df["ExperienceYears"] = df["ExperienceYears"].astype(str).replace("five","5", regex=False)
df["ExperienceYears"] = pd.to_numeric(df["ExperienceYears"], errors="coerce")
df["ExperienceYears"] = df["ExperienceYears"].fillna(df["ExperienceYears"].mean())
df["ExperienceYears"] = df["ExperienceYears"].round(0).astype(int)

In [24]:
df.isnull().sum()

EmployeeID            0
Name                  0
Age                   0
City                 33
Department            0
Salary                0
JoinDate             58
Email                84
PerformanceRating     0
ExperienceYears       0
dtype: int64

In [25]:
df.tail(20)

,EmployeeID,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating,ExperienceYears
1069,1290,Swati Reddy,24.000000,Bangalore,IT,76906.000000,1/6/2020,swati.reddy51@gmail.com,1.0,12
1070,1763,Rekha Joshi,26.000000,pune,IT,22077.000000,21 Jan 2019,NaN,2.0,3
1071,1949,Sohail Iyer,26.000000,Ahmedabad,sales,114492.000000,9/3/2025,sohail.iyer22@gmail.com,3.0,10
1072,1183,Anita Singh,40.000000,Bangalore,Sales,132272.000000,3/3/2020,anita.singh51@gmail.com,3.0,20
1074,2030,Nikhil Bhat,44.000000,Hyderabad,HR,23544.000000,2/24/2019,NaN,1.0,7
1075,1250,Simran Singh,40.171843,Jaipur,IT,67118.000000,24-11-2017,simran.singh58@gmail.com,3.0,2
1076,1823,Preeti Kapoor,44.000000,Bangalore,Hr,88214.000000,11 Jan 2015,NaN,3.0,20
1077,1940,Jyoti Reddy,27.000000,Pune,IT,84410.763407,15 Jan 2025,jyotireddygmail.com,5.0,16
1078,1391,Vivek Rao,29.000000,Chennai,Finance,103394.000000,10-01-2020,vivek.rao10@gmail.com,2.0,12
1079,1904,Pooja Pillai,52.000000,Hyderabad,IT,50816.000000,4/20/2019,pooja.pillai77@gmail.com,4.0,2
1080,1730,Rajesh Saxena,44.000000,pune,Operations,89796.000000,2021-04-28,rajesh.saxena37@gmail.com,4.0,18
1081,1554,Rakesh Singh,21.000000,Delhi,Marketing,87412.000000,4 Jan 2017,NaN,3.0,8
1082,1366,Anjali Pillai,34.000000,Mumbai,Hr,51359.000000,NaN,anjali.pillai64@gmail.com,1.0,16
1083,1345,Sohail Patel,48.000000,Bangalore,IT,79558.000000,7/18/2023,sohail.patel29@gmail.com,5.0,10
1084,1535,Nikhil Malhotra,54.000000,MUMBAI,Marketing,91828.000000,05-02-2021,nikhil.malhotra7@gmail.com,3.0,3
1085,1919,Meera Desai,55.000000,Kolkata,sales,56477.000000,26-06-2016,meera.desai25@gmail.com,3.0,18
1086,1211,Vivek Nair,40.000000,Jaipur,Marketing,125569.000000,22-07-2024,vivek.nair4@gmail.com,3.0,8
1087,1502,Sameer Bhat,31.000000,Delhi,Hr,62731.000000,06-08-2021,sameer.bhat60@gmail.com,3.0,14
1088,1537,Sneha Gupta,51.000000,Mumbai,IT,105209.000000,14 Jan 2020,sneha.gupta52@gmail.com,1.0,10
1089,1175,Vishal Sharma,43.000000,Ahmedabad,Finance,36637.000000,12/4/2019,NaN,3.0,5

In [26]:
df["City"].unique()

array(['Mumbai', '  Bangalore', 'Nagpur', 'MUMBAI', 'pune', 'Delhi',
       'Chennai', 'Hyderabad', 'Delhi ', nan, 'Pune', 'Bangalore',
       'Kolkata', 'Jaipur', 'Ahmedabad'], dtype=object)

In [27]:
df["City"] = df["City"].str.strip()
df["City"] = df["City"].str.title()
df["City"] = df["City"].fillna("Unknown")

In [28]:
df["Email"] = df["Email"].fillna("Not Provided")

In [29]:
df["JoinDate"] = pd.to_datetime(df["JoinDate"], format="mixed", dayfirst=False, errors="coerce")

In [30]:
df.isnull().sum()

EmployeeID            0
Name                  0
Age                   0
City                  0
Department            0
Salary                0
JoinDate             58
Email                 0
PerformanceRating     0
ExperienceYears       0
dtype: int64

In [31]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
Index: 1051 entries, 0 to 1089
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         1051 non-null   int64
 1   Name               1051 non-null   object
 2   Age                1051 non-null   float64
 3   City               1051 non-null   object
 4   Department         1051 non-null   object
 5   Salary             1051 non-null   float64
 6   JoinDate           993 non-null    datetime64[ns]
 7   Email              1051 non-null   object
 8   PerformanceRating  1051 non-null   float64
 9   ExperienceYears    1051 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(2), object(4)
memory usage: 90.3+ KB

(1051, 10)

In [32]:
df["Age"] = df["Age"].round(0)
df["Salary"] = df["Salary"].round(2)

In [33]:
df["Department"] = df["Department"].str.strip().str.title()

In [34]:
df["Department"].unique()

array(['Operations', 'Hr', 'It', 'Finance', 'Sales', 'Marketing'],
      dtype=object)

In [35]:
df["Department"] = df["Department"].replace({"It": "IT", "Hr": "HR"})

In [36]:
df.to_excel("cleaned_employee_data.xlsx", index=False)

In [37]:
df.head()

,EmployeeID,Name,Age,City,Department,Salary,JoinDate,Email,PerformanceRating,ExperienceYears
0,1714,Pooja Reddy,36.0,Mumbai,Operations,84410.76,2020-02-16,pooja.reddy28@gmail.com,4.0,14
1,1978,Yash Malhotra,25.0,Bangalore,HR,75830.00,2016-11-27,yash.malhotra25@gmail.com,3.0,20
2,1936,Swati Malhotra,40.0,Nagpur,IT,57068.00,2019-01-25,swati.malhotra79@gmail.com,5.0,13
3,1866,Harsh Verma,28.0,Mumbai,HR,58455.00,2017-01-10,harsh.verma88@gmail.com,1.0,10
4,1700,Tanvi Rao,37.0,Pune,IT,43332.00,2015-06-28,tanvi.rao94@gmail.com,5.0,20

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1051 entries, 0 to 1089
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         1051 non-null   int64
 1   Name               1051 non-null   object
 2   Age                1051 non-null   float64
 3   City               1051 non-null   object
 4   Department         1051 non-null   object
 5   Salary             1051 non-null   float64
 6   JoinDate           993 non-null    datetime64[ns]
 7   Email              1051 non-null   object
 8   PerformanceRating  1051 non-null   float64
 9   ExperienceYears    1051 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(2), object(4)
memory usage: 90.3+ KB